# Generated by Django 3.1.1 on 2020-09-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('at_research_visualiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='reasoning',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='georesult',
            name='outcome_definition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='at_research_visualiser.outcomedefinition'),
        ),
    ]
